[fetch]
url = "http://www.itokoo.com/read.php?tid=188"
regexp = '''(?s)<a href="([^"]*?)" target="_blank" >[^\d]*?(\d{4})\.\d+.\d+ No\.(\d+) (\w+)'''
sets = ["sectionURL", "year", "no", "name"]
parallel = 0
debug = false

[fetch.exists]
path="$root/$year/${no}_$name.rar"
continue=false
debug=true

[fetch.exists.fetch]
url = "$sectionURL"
regexp = '''href="(https://itokoo\.ctfile\.com/fs/(\d+)\-(\d+))" target="_blank" >'''
sets = ["wpURL", "uid", "fid"]
debug = false

[fetch.exists.fetch.fetch]
url = "$wpURL"
regexp = '''(?s)free_down\('\w+', 0, '(\w+)', 0, 0\)'''
sets = ["file_chk"]
debug = false

[fetch.exists.fetch.fetch.fetch]
url = "https://itokoo.ctfile.com/get_file_url.php?uid=$uid&fid=$fid&folder_id=0&fid=$fid&file_chk=$file_chk&mb=0&app=0&verifycode=&rd=0.02884385309092985"
regexp = '''(?s)downurl":"([^"]+?)"'''
sets = ["downloadURL"]
debug = false

[fetch.exists.fetch.fetch.fetch.replace]
expression = "$downloadURL"
old = "\\/"
new = "/"
set = "downloadURL1"
debug = true

[[fetch.exists.fetch.fetch.fetch.execute]]
command = "mkdir"
args = ["-p", "$root/$year"]
debug = true

[[fetch.exists.fetch.fetch.fetch.execute]]
command = "aria2c"
args = ["-d", "$root/$year", "-o", "${no}_$name.downloading", "$downloadURL1"]
debug = true

[[fetch.exists.fetch.fetch.fetch.execute]]
command = "mv"
args = ["$root/$year/${no}_$name.downloading", "$root/$year/${no}_$name.rar"]
debug = true